# Generated by Django 3.1.7 on 2021-12-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.FloatField()),
                ('product_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_stripe_id', models.CharField(blank=True, max_length=300, null=True)),
                ('product_stripe_price_id', models.CharField(blank=True, max_length=300, null=True)),
                ('featured', models.BooleanField(blank=True, default=False, null=True)),
                ('max_keywords', models.IntegerField(default=0)),
                ('max_results', models.IntegerField(default=0)),
                ('max_countries', models.IntegerField(default=0)),
                ('check_interval', models.CharField(choices=[('daily', 'Daily'), ('twiceaday', 'Twice a Day'), ('hourly', 'Hourly'), ('sixhours', 'Six Hours')], default='daily', max_length=20)),
                ('realtime_checks', models.IntegerField(default=0)),
                ('multiple_devices', models.BooleanField(default=False)),
            ],
        ),
    ]
